# Clippy Configuration for vi-engine
# Enforces the highest standards of Rust code quality

# Cognitive complexity threshold - keep functions simple
cognitive-complexity-threshold = 15

# Maximum number of lines for a function
too-many-lines-threshold = 80

# Maximum number of arguments for a function
too-many-arguments-threshold = 5

# Minimum number of enum variants to trigger large enum variant warning
enum-variant-size-threshold = 200

# Trivial copy threshold
trivial-copy-size-limit = 128

# Allow expect in tests
allow-expect-in-tests = true

# Allow unwrap in tests
allow-unwrap-in-tests = true

# Disallow certain unsafe operations
avoid-breaking-exported-api = true
