# cargo-deny configuration for vi-engine
# Ensures security, licensing, and dependency management best practices

[graph]
# Exclude dev dependencies from analysis in some contexts
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
# Security vulnerability database
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "all"
yanked = "warn"
ignore = [
    # Add any specific advisories to ignore here if needed
    # "RUSTSEC-YYYY-NNNN",
]

[licenses]
# License policy - allow common open-source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "0BSD",
    "CC0-1.0",
    "Zlib",
    "Unlicense",
]
confidence-threshold = 0.8
unused-allowed-license = "allow"

[bans]
# Dependency management
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = [
    # Deny problematic crates
    { name = "openssl", reason = "Use rustls instead" },
    { name = "native-tls", reason = "Use rustls instead" },
    { name = "reqwest", version = "<0.11", reason = "Use newer version" },
]

# Skip certain crates from duplicate version checking
skip = [
    # Add crates here if they have multiple versions that are acceptable
]

skip-tree = [
    # Skip entire dependency trees that commonly have version conflicts
    { name = "criterion" },
    { name = "rustyline" },
]

[sources]
# Source code policy
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
