# cargo-deny configuration for vi-engine
# Ensures security, licensing, and dependency management best practices

[graph]
# Exclude dev dependencies from analysis in some contexts
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
# Security vulnerability database
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    # Add any specific advisories to ignore here if needed
    # "RUSTSEC-YYYY-NNNN",
]

[licenses]
# License policy - be restrictive but practical
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "MPL-2.0",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
# Dependency management
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
    # Allow specific crates that might have multiple versions
    { name = "windows-sys" },
    { name = "windows_x86_64_msvc" },
    { name = "windows_aarch64_msvc" },
]
deny = [
    # Deny problematic crates
    { name = "openssl", reason = "Use rustls instead" },
    { name = "native-tls", reason = "Use rustls instead" },
    { name = "reqwest", version = "<0.11", reason = "Use newer version" },
]

# Skip certain crates from duplicate version checking
skip = [
    { name = "windows-sys" },
    { name = "bitflags" },
]

skip-tree = [
    # Skip entire dependency trees that commonly have version conflicts
    { name = "criterion" },
    { name = "rustyline" },
]

[sources]
# Source code policy
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
